In [3]:
from selenium import webdriver
from selenium.webdriver.support.ui import Select

In [4]:
browser = webdriver.Chrome()
url = "http://rate.am/en/armenian-dram-exchange-rates/banks/non-cash"
browser.get(url)

In [5]:
data=browser.find_element_by_xpath('//*[@id="aspnetForm"]/div[3]/div[2]/div[1]/div[4]/div[3]/table/tbody/tr/td[1]/a')
data.click()
data_1=browser.find_element_by_xpath('//*[@id="calBorder"]/span/table/tbody/tr[3]/td/table/tbody/tr[5]/td[4]')
data_1.click()
data_2=browser.find_element_by_xpath('//*[@id="ctl00_Content_RB_dtpick1_btnOk"]')
data_2.click()

In [6]:
import pandas as pd

In [11]:
rates_table=pd.read_html(browser.find_element_by_class_name("rb").get_attribute('outerHTML'))
rates_table = rates_table[0]
rates_table = rates_table[2:19] 
del rates_table[0]
del rates_table[2]
del rates_table[3]

In [13]:
rates_table.columns = ["Բանկ", "Ամսաթիվ", "USD_Առք", "USD_Վաճ", "EUR_Առք", "EUR_Վաճ", "RUB_Առք", "RUB_Վաճ", "GBF_Առք", "GBF_Վաճ"]

In [15]:
rates_table

,Բանկ,Ամսաթիվ,USD_Առք,USD_Վաճ,EUR_Առք,EUR_Վաճ,RUB_Առք,RUB_Վաճ,GBF_Առք,GBF_Վաճ
2,Էյչ-Էս-Բի-Սի Բանկ,"20 Jul, 20:01",476.50,480.50,550,558.0,7.99,8.23,616.5,625.5
3,ՀԱՅԲԻԶՆԵՍԲԱՆԿ ՓԲԸ,"20 Jul, 20:00",477,480,547.10,554.1,8.02,8.24,617.1,629.1
4,Կոնվերս բանկ,"20 Jul, 20:00",476.50,480,547,555.0,8.02,8.21,619.0,627.0
5,Յունիբանկ,"20 Jul, 20:00",476.50,480,546,556.0,8.00,8.25,612.0,632.0
6,Արցախբանկ,"20 Jul, 20:00",477,480,547,555.0,7.99,8.20,614.0,629.0
7,Անելիք Բանկ,"20 Jul, 20:00",477,480.50,546,556.0,8.04,8.22,NaN,NaN
8,ԱԿԲԱ-ԿՐԵԴԻՏ ԱԳՐԻԿՈԼ ..,"20 Jul, 20:00",477,480.50,546.50,554.0,8.05,8.18,612.0,627.0
9,Արմսվիսբանկ,"20 Jul, 20:00",477,480,548,554.0,8.04,8.22,617.0,624.0
10,Բիբլոս Բանկ Արմենիա,"20 Jul, 20:00",477,480.50,547,555.0,7.99,8.24,618.0,629.0
11,Ամերիաբանկ,"20 Jul, 20:00",476.50,480.50,551.50,559.5,7.97,8.22,616.5,626.5
12,Արդշինբանկ,"20 Jul, 20:00",477.50,480.50,548,558.0,7.97,8.22,618.0,633.0
13,Պրոմեթեյ Բանկ,"20 Jul, 20:00",477,480,548,556.0,8.06,8.16,614.0,625.0
14,ԱՐԱՐԱՏԲԱՆԿ,"20 Jul, 20:00",477.50,480.50,543,561.0,8.04,8.25,610.0,633.0
15,ՀԱՅԷԿՈՆՈՄԲԱՆԿ,"20 Jul, 20:00",477,480.50,547,555.0,8.06,8.23,611.0,630.0
16,ՎՏԲ-Հայաստան Բանկ,"20 Jul, 20:00",477.25,480,547,553.5,8.06,8.18,619.0,630.0
17,Ինեկոբանկ,"20 Jul, 20:00",477.25,480.25,547,559.0,7.95,8.20,613.0,626.0
18,Մելլաթ բանկ,"20 Jul, 20:00",476,480,547,555.0,NaN,NaN,NaN,NaN

In [19]:
import csv
import unicodecsv
with open('rate_tables.csv', 'w') as f:
            rates_table.to_csv(f, header=True, index=False, encoding='utf-8')